FROM python:3.7-slim

WORKDIR /app/miro

COPY backend/run.py ./
COPY requirements.txt ./

RUN apt-get update && apt-get install python3-pip && apt-get install tmux
RUN pip3 install -r requirements.txt

