
FROM nvcr.io/nvidia/pytorch:21.07-py3
ENV NVIDIA_VISIBLE_DEVICES all

WORKDIR /app/miro

COPY backend/run.py ./
COPY requirements.txt ./

RUN apt-get update && apt-get install python3-pip && apt-get install tmux
RUN pip3 install -r requirements.txt
